import { MetricasRegionais } from './types';

export const METRICAS_SUBPREFEITURAS_SP: MetricasRegionais[] = [
  {
    subprefeituraId: '1',
    nome: 'Sé',
    zona: 'CENTRO',
    populacao: 431106,
    totalDemandas: 342,
    demandasPor10k: 7.9,
    tmaHoras: 31.4,
    slaCumpridoPercentual: 88.5,
    taxaReincidenciaPercentual: 6.2,
    taxaResolucaoPercentual: 91.2,
    chamadosAbertos: 48,
    chamadosConcluidos: 294,
    criticidadeAlta: 38
  },
  {
    subprefeituraId: '2',
    nome: 'Vila Mariana',
    zona: 'SUL',
    populacao: 293309,
    totalDemandas: 215,
    demandasPor10k: 7.3,
    tmaHoras: 26.8,
    slaCumpridoPercentual: 93.4,
    taxaReincidenciaPercentual: 4.1,
    taxaResolucaoPercentual: 94.6,
    chamadosAbertos: 22,
    chamadosConcluidos: 193,
    criticidadeAlta: 19
  },
  {
    subprefeituraId: '3',
    nome: 'Mooca',
    zona: 'LESTE',
    populacao: 350567,
    totalDemandas: 284,
    demandasPor10k: 8.1,
    tmaHoras: 34.2,
    slaCumpridoPercentual: 86.2,
    taxaReincidenciaPercentual: 7.8,
    taxaResolucaoPercentual: 88.9,
    chamadosAbertos: 41,
    chamadosConcluidos: 243,
    criticidadeAlta: 34
  },
  {
    subprefeituraId: '4',
    nome: 'Pinheiros',
    zona: 'OESTE',
    populacao: 289743,
    totalDemandas: 198,
    demandasPor10k: 6.8,
    tmaHoras: 24.5,
    slaCumpridoPercentual: 95.1,
    taxaReincidenciaPercentual: 3.5,
    taxaResolucaoPercentual: 96.0,
    chamadosAbertos: 18,
    chamadosConcluidos: 180,
    criticidadeAlta: 15
  },
  {
    subprefeituraId: '5',
    nome: 'Lapa',
    zona: 'OESTE',
    populacao: 305536,
    totalDemandas: 226,
    demandasPor10k: 7.4,
    tmaHoras: 28.9,
    slaCumpridoPercentual: 91.0,
    taxaReincidenciaPercentual: 5.2,
    taxaResolucaoPercentual: 92.3,
    chamadosAbertos: 29,
    chamadosConcluidos: 197,
    criticidadeAlta: 24
  },
  {
    subprefeituraId: '6',
    nome: 'Butantã',
    zona: 'OESTE',
    populacao: 378178,
    totalDemandas: 260,
    demandasPor10k: 6.9,
    tmaHoras: 30.1,
    slaCumpridoPercentual: 89.8,
    taxaReincidenciaPercentual: 5.9,
    taxaResolucaoPercentual: 90.7,
    chamadosAbertos: 36,
    chamadosConcluidos: 224,
    criticidadeAlta: 27
  },
  {
    subprefeituraId: '7',
    nome: 'Campo Limpo',
    zona: 'SUL',
    populacao: 607105,
    totalDemandas: 410,
    demandasPor10k: 6.7,
    tmaHoras: 42.5,
    slaCumpridoPercentual: 81.4,
    taxaReincidenciaPercentual: 9.3,
    taxaResolucaoPercentual: 84.1,
    chamadosAbertos: 75,
    chamadosConcluidos: 335,
    criticidadeAlta: 52
  },
  {
    subprefeituraId: '8',
    nome: 'Capela do Socorro',
    zona: 'SUL',
    populacao: 594930,
    totalDemandas: 395,
    demandasPor10k: 6.6,
    tmaHoras: 44.1,
    slaCumpridoPercentual: 79.8,
    taxaReincidenciaPercentual: 10.1,
    taxaResolucaoPercentual: 82.5,
    chamadosAbertos: 82,
    chamadosConcluidos: 313,
    criticidadeAlta: 56
  },
  {
    subprefeituraId: '9',
    nome: 'Itaquera',
    zona: 'LESTE',
    populacao: 523882,
    totalDemandas: 388,
    demandasPor10k: 7.4,
    tmaHoras: 39.7,
    slaCumpridoPercentual: 83.1,
    taxaReincidenciaPercentual: 8.4,
    taxaResolucaoPercentual: 85.6,
    chamadosAbertos: 64,
    chamadosConcluidos: 324,
    criticidadeAlta: 47
  },
  {
    subprefeituraId: '10',
    nome: 'Santana / Tucuruvi',
    zona: 'NORTE',
    populacao: 324815,
    totalDemandas: 242,
    demandasPor10k: 7.4,
    tmaHoras: 29.3,
    slaCumpridoPercentual: 90.5,
    taxaReincidenciaPercentual: 5.0,
    taxaResolucaoPercentual: 91.8,
    chamadosAbertos: 31,
    chamadosConcluidos: 211,
    criticidadeAlta: 26
  },
  {
    subprefeituraId: '11',
    nome: 'Freguesia / Brasilândia',
    zona: 'NORTE',
    populacao: 410410,
    totalDemandas: 335,
    demandasPor10k: 8.1,
    tmaHoras: 38.6,
    slaCumpridoPercentual: 84.7,
    taxaReincidenciaPercentual: 8.0,
    taxaResolucaoPercentual: 86.9,
    chamadosAbertos: 53,
    chamadosConcluidos: 282,
    criticidadeAlta: 41
  },
  {
    subprefeituraId: '12',
    nome: 'Santo Amaro',
    zona: 'SUL',
    populacao: 238025,
    totalDemandas: 185,
    demandasPor10k: 7.7,
    tmaHoras: 27.2,
    slaCumpridoPercentual: 92.8,
    taxaReincidenciaPercentual: 4.6,
    taxaResolucaoPercentual: 93.5,
    chamadosAbertos: 21,
    chamadosConcluidos: 164,
    criticidadeAlta: 20
  },
  {
    subprefeituraId: '13',
    nome: 'Ipiranga',
    zona: 'SUL',
    populacao: 463804,
    totalDemandas: 312,
    demandasPor10k: 6.7,
    tmaHoras: 32.1,
    slaCumpridoPercentual: 88.2,
    taxaReincidenciaPercentual: 6.4,
    taxaResolucaoPercentual: 89.7,
    chamadosAbertos: 44,
    chamadosConcluidos: 268,
    criticidadeAlta: 35
  },
  {
    subprefeituraId: '14',
    nome: 'Penha',
    zona: 'LESTE',
    populacao: 472500,
    totalDemandas: 356,
    demandasPor10k: 7.5,
    tmaHoras: 35.8,
    slaCumpridoPercentual: 85.9,
    taxaReincidenciaPercentual: 7.1,
    taxaResolucaoPercentual: 87.6,
    chamadosAbertos: 55,
    chamadosConcluidos: 301,
    criticidadeAlta: 42
  },
  {
    subprefeituraId: '15',
    nome: 'São Miguel Paulista',
    zona: 'LESTE',
    populacao: 369400,
    totalDemandas: 310,
    demandasPor10k: 8.4,
    tmaHoras: 39.2,
    slaCumpridoPercentual: 82.4,
    taxaReincidenciaPercentual: 8.7,
    taxaResolucaoPercentual: 85.1,
    chamadosAbertos: 58,
    chamadosConcluidos: 252,
    criticidadeAlta: 45
  },
  {
    subprefeituraId: '16',
    nome: 'Pirituba / Jaraguá',
    zona: 'NORTE',
    populacao: 437500,
    totalDemandas: 325,
    demandasPor10k: 7.4,
    tmaHoras: 36.4,
    slaCumpridoPercentual: 85.1,
    taxaReincidenciaPercentual: 7.6,
    taxaResolucaoPercentual: 87.2,
    chamadosAbertos: 49,
    chamadosConcluidos: 276,
    criticidadeAlta: 39
  },
  {
    subprefeituraId: '17',
    nome: 'Jabaquara',
    zona: 'SUL',
    populacao: 223700,
    totalDemandas: 198,
    demandasPor10k: 8.8,
    tmaHoras: 30.5,
    slaCumpridoPercentual: 89.4,
    taxaReincidenciaPercentual: 6.0,
    taxaResolucaoPercentual: 91.0,
    chamadosAbertos: 27,
    chamadosConcluidos: 171,
    criticidadeAlta: 25
  },
  {
    subprefeituraId: '18',
    nome: 'Vila Prudente',
    zona: 'LESTE',
    populacao: 232600,
    totalDemandas: 195,
    demandasPor10k: 8.3,
    tmaHoras: 29.8,
    slaCumpridoPercentual: 90.2,
    taxaReincidenciaPercentual: 5.7,
    taxaResolucaoPercentual: 91.5,
    chamadosAbertos: 26,
    chamadosConcluidos: 169,
    criticidadeAlta: 23
  },
  {
    subprefeituraId: '19',
    nome: 'Ermelino Matarazzo',
    zona: 'LESTE',
    populacao: 207400,
    totalDemandas: 184,
    demandasPor10k: 8.8,
    tmaHoras: 37.9,
    slaCumpridoPercentual: 83.5,
    taxaReincidenciaPercentual: 8.2,
    taxaResolucaoPercentual: 86.0,
    chamadosAbertos: 32,
    chamadosConcluidos: 152,
    criticidadeAlta: 29
  },
  {
    subprefeituraId: '20',
    nome: 'Cidade Tiradentes',
    zona: 'LESTE',
    populacao: 211500,
    totalDemandas: 205,
    demandasPor10k: 9.7,
    tmaHoras: 43.8,
    slaCumpridoPercentual: 78.4,
    taxaReincidenciaPercentual: 9.8,
    taxaResolucaoPercentual: 81.2,
    chamadosAbertos: 46,
    chamadosConcluidos: 159,
    criticidadeAlta: 38
  },
  {
    subprefeituraId: '21',
    nome: 'São Mateus',
    zona: 'LESTE',
    populacao: 426400,
    totalDemandas: 348,
    demandasPor10k: 8.1,
    tmaHoras: 41.2,
    slaCumpridoPercentual: 81.9,
    taxaReincidenciaPercentual: 9.1,
    taxaResolucaoPercentual: 84.3,
    chamadosAbertos: 61,
    chamadosConcluidos: 287,
    criticidadeAlta: 46
  },
  {
    subprefeituraId: '22',
    nome: 'Guaianases',
    zona: 'LESTE',
    populacao: 268500,
    totalDemandas: 238,
    demandasPor10k: 8.8,
    tmaHoras: 42.1,
    slaCumpridoPercentual: 79.5,
    taxaReincidenciaPercentual: 9.5,
    taxaResolucaoPercentual: 82.8,
    chamadosAbertos: 48,
    chamadosConcluidos: 190,
    criticidadeAlta: 36
  },
  {
    subprefeituraId: '23',
    nome: 'Itaim Paulista',
    zona: 'LESTE',
    populacao: 373100,
    totalDemandas: 318,
    demandasPor10k: 8.5,
    tmaHoras: 44.5,
    slaCumpridoPercentual: 78.1,
    taxaReincidenciaPercentual: 10.2,
    taxaResolucaoPercentual: 81.5,
    chamadosAbertos: 67,
    chamadosConcluidos: 251,
    criticidadeAlta: 49
  },
  {
    subprefeituraId: '24',
    nome: 'Cidade Ademar',
    zona: 'SUL',
    populacao: 410700,
    totalDemandas: 334,
    demandasPor10k: 8.1,
    tmaHoras: 40.8,
    slaCumpridoPercentual: 82.7,
    taxaReincidenciaPercentual: 8.9,
    taxaResolucaoPercentual: 85.2,
    chamadosAbertos: 57,
    chamadosConcluidos: 277,
    criticidadeAlta: 44
  },
  {
    subprefeituraId: '25',
    nome: 'Parelheiros',
    zona: 'SUL',
    populacao: 154800,
    totalDemandas: 162,
    demandasPor10k: 10.4,
    tmaHoras: 48.6,
    slaCumpridoPercentual: 74.5,
    taxaReincidenciaPercentual: 11.4,
    taxaResolucaoPercentual: 78.0,
    chamadosAbertos: 42,
    chamadosConcluidos: 120,
    criticidadeAlta: 33
  },
  {
    subprefeituraId: '26',
    nome: "M'Boi Mirim",
    zona: 'SUL',
    populacao: 563400,
    totalDemandas: 420,
    demandasPor10k: 7.4,
    tmaHoras: 45.2,
    slaCumpridoPercentual: 77.9,
    taxaReincidenciaPercentual: 10.5,
    taxaResolucaoPercentual: 80.9,
    chamadosAbertos: 89,
    chamadosConcluidos: 331,
    criticidadeAlta: 58
  },
  {
    subprefeituraId: '27',
    nome: 'Casa Verde / Cachoeirinha',
    zona: 'NORTE',
    populacao: 309300,
    totalDemandas: 245,
    demandasPor10k: 7.9,
    tmaHoras: 33.4,
    slaCumpridoPercentual: 87.8,
    taxaReincidenciaPercentual: 6.8,
    taxaResolucaoPercentual: 89.2,
    chamadosAbertos: 34,
    chamadosConcluidos: 211,
    criticidadeAlta: 28
  },
  {
    subprefeituraId: '28',
    nome: 'Jaçanã / Tremembé',
    zona: 'NORTE',
    populacao: 291900,
    totalDemandas: 238,
    demandasPor10k: 8.1,
    tmaHoras: 35.1,
    slaCumpridoPercentual: 86.4,
    taxaReincidenciaPercentual: 7.3,
    taxaResolucaoPercentual: 88.0,
    chamadosAbertos: 36,
    chamadosConcluidos: 202,
    criticidadeAlta: 30
  },
  {
    subprefeituraId: '29',
    nome: 'Perus',
    zona: 'NORTE',
    populacao: 146500,
    totalDemandas: 154,
    demandasPor10k: 10.5,
    tmaHoras: 46.0,
    slaCumpridoPercentual: 76.2,
    taxaReincidenciaPercentual: 10.9,
    taxaResolucaoPercentual: 79.5,
    chamadosAbertos: 38,
    chamadosConcluidos: 116,
    criticidadeAlta: 31
  },
  {
    subprefeituraId: '30',
    nome: 'Vila Maria / Vila Guilherme',
    zona: 'NORTE',
    populacao: 297700,
    totalDemandas: 236,
    demandasPor10k: 7.9,
    tmaHoras: 31.8,
    slaCumpridoPercentual: 88.9,
    taxaReincidenciaPercentual: 6.5,
    taxaResolucaoPercentual: 90.4,
    chamadosAbertos: 30,
    chamadosConcluidos: 206,
    criticidadeAlta: 27
  },
  {
    subprefeituraId: '31',
    nome: 'Aricanduva / Formosa / Carrão',
    zona: 'LESTE',
    populacao: 267700,
    totalDemandas: 228,
    demandasPor10k: 8.5,
    tmaHoras: 33.0,
    slaCumpridoPercentual: 87.5,
    taxaReincidenciaPercentual: 7.0,
    taxaResolucaoPercentual: 89.8,
    chamadosAbertos: 31,
    chamadosConcluidos: 197,
    criticidadeAlta: 29
  },
  {
    subprefeituraId: '32',
    nome: 'Sapopemba',
    zona: 'LESTE',
    populacao: 284500,
    totalDemandas: 254,
    demandasPor10k: 8.9,
    tmaHoras: 41.5,
    slaCumpridoPercentual: 80.8,
    taxaReincidenciaPercentual: 9.4,
    taxaResolucaoPercentual: 83.6,
    chamadosAbertos: 50,
    chamadosConcluidos: 204,
    criticidadeAlta: 37
  }
];
